# Generated by Django 5.1.1 on 2024-10-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/avatarImg.jpg', upload_to='avatars/'),
        ),
    ]
